### ISSUE TITLE
Move this project into the mongoid organization?

### ISSUE THREAD

**Issue by dblock** [mongoid/mongoid_orderable#46]
@pyromaniac I now co-own https://github.com/mongoid with some MongoDB people. Are you interested in moving this project into that org? It would allow some more maintainers that can give r/w access to this project and would help discoverability. Just trying to reduce bus factor ;)

**Comment by pyromaniac** [comment]
Sure, why not, what to I have to do? I mean I'm not working with mongo for a while already, but if this gem is really helpful, it should continue to help people.

**Comment by dblock** [comment]
@pyromaniac I invited you to the mongoid org, join, then transfer the project to the org, then re-fork it into your own place. I'll remove org ownership privileges after and check all permissions. 

Add me (dblock@dblock.org), Emily (emily@mongodb.com) and Durran (durran@gmail.com) to gem owners, too, please.

**Comment by pyromaniac** [comment]
I did everything, now can I have my passport back?

Also, Durran was added strangely:

```
gem owner mongoid_orderable
Owners for gem: mongoid_orderable
-
- emily@mongodb.com
- dblock@dblock.org
- kinwizard@gmail.com
```

**Comment by dblock** [comment]
Thanks!

yeah, Durran's email is private, that's why. Nice email you have ;) 

Everything looks good now, you have admin privileges on the parent repo too.

Need to s/piromaniac/mongoid/g for things like badges, if you're bored would appreciate if you could do it, otherwise no stress we'll fix them as we go.

**Comment by pyromaniac** [comment]
Can't promise anything, unfortunately, I'm extremely busy nowadays. I'm proud of sharing this gem with the community.

**Comment by dblock** [comment]
thank you @pyromaniac !
