### ISSUE TITLE
can I use mongoid_orderable in hash field?

### ISSUE THREAD

**Issue by xiaok** [mongoid/mongoid_orderable#48]
I have lots of `records`, they have different position in different table.

so the schema is like:

```
class Record
  field :tables, type: Hash, default: {}
  #tables: {
  #   [table_id]: { position: 0, hide: true }
  #}
end
```

can I use mongoid_orderable in Record.tables[table_id].position?

**Comment by pyromaniac** [comment]
If you will define tables with embeds_many - then yes.
