### ISSUE TITLE
undefined method mongoid7? for an installation of Mongoid at 6.4.X

### ISSUE THREAD

**Issue by tigerfishsync** [mongoid/mongoid_orderable#58]
Hi there, when I tried to start a rails app after `bundle install` it errors out like this:

`gems/mongoid_orderable-5.2.0/lib/mongoid_orderable.rb:18:in `<module:MongoidOrderable>': undefined method `mongoid7?' for Mongoid::Compatibility::Version:Module (NoMethodError)`

This is against a `mongoid` gem at `6.4.4`

diving into the code base, at line 18 of `mongoid_orderable.rb` it does show that it's checking against mongoid 7 only.

<img width="460" alt="image" src="https://user-images.githubusercontent.com/472936/86152217-21390300-bb00-11ea-9cb4-4748e3ff1496.png">

Does anyone else have the same problem?

**Comment by dblock** [comment]
What version of mongoid-compatibility are you bringing in? It should be 0.5.0 or newer. Maybe not loaded in order?

https://github.com/mongoid/mongoid-compatibility/blob/master/CHANGELOG.md

**Comment by dblock** [comment]
Does look like we forgot to set the minimum version of mongoid-compatibility to 0.5.0 in https://github.com/mongoid/mongoid_orderable/pull/57. Care to fix?

**Comment by niksosf** [comment]
Hi there, I have the same problem and my `mongoid-compatibility` is at `0.4.1`.

**Comment by dblock** [comment]
Please @niksosf !

**Comment by johnnyshields** [comment]
Support for Mongoid 6.x.x will be dropped as of Mongoid::Orderable 6.0.0, and Mongoid::Compatibility will no longer be used. If you'd like to raise a PR for Mongoid::Orderable 5.2.0 branch I'd be happy to release a fix as version 5.2.1. Closing this issue.
